.circleci/config.yml
config.yml

Add orb slack-notify-waiting-for-approval

---

config.yml

Fixup typos in config script
@chrisleck PTAL

Fixup typos

---

config.yml

Finally have this working - wasn't substituting the parameters correctly 🤦‍♂️
Published as coda/utils@0.0.15
@chrisleck PTAL

Fixup orb parameter subst -- published as coda/utils@0.0.15

---

src/commands/notify.yml

Add outcome key to details; global policy cannot parse payload unless outcome is in key/value (https://krypton.app.opsgenie.com/settings/integration/edit/API/23728dd9-b742-4d64-b95f-27107922ac68)
Fix alerts on all cases -- only failing cases.

Add details outcome key; [semver:patch]

---

src/scripts/fetch_user_handles.sh

Fix jq issue related to chaining w/ curl: see https://github.com/stedolan/jq/issues/501
https://app.circleci.com/pipelines/github/kr-project/experimental/112176/workflows/cbf41aea-4cdf-4b51-b1cb-80c3552c8887/jobs/511773

jq curl issue fix; [semver:patch]

---

.circleci/config.yml
README.md
src/commands/notify.yml
src/commands/slack-notify-waiting-for-approval.yml
src/jobs/slack-notify-waiting-for-approval.yml
src/scripts/fetch_user_handles.sh
src/tests/test_user_handles.bats

Alert opsgenie responder based on Git PR breaks (either author or reviewer based on whether it was a bot break or Codan break).

Add opsgenie responder based on PR break 

---

.github/pull_request_template.md

forgot to add semver [semver:minor] in pr title

forgot to add semver [semver:minor]

---

src/commands/notify.yml

Add team [semver:patch]

---

src/commands/notify.yml
src/commands/slack-notify-waiting-for-approval.yml
src/examples/example.yml
src/jobs/slack-notify-waiting-for-approval.yml
src/scripts/fetch_user_handles.sh
src/tests/test_user_handles.bats

jq & roster fix [semver:patch]

---

src/commands/notify.yml
src/scripts/fetch_user_handles.sh

Fix bug when there is a comment with spaces for pr reviews & set responder only on fail

Fix spacing when there is a comment [semver:patch]

---

src/commands/notify.yml

change close alert api 
auto closing not occurring

closing alert has diff endpoint [semver:patch]

---

src/commands/notify.yml

https://app.circleci.com/pipelines/github/kr-project/experimental/117483/workflows/6273af1f-5b05-484c-9ed4-b74686f443f7/jobs/542736

Fix File Path [semver:patch]

---

src/commands/notify.yml

forgot to add semver in title 🙃

fix file [semver:patch]

---

src/commands/notify.yml

last one I swear
🙃 identifier type close alert

idenitifer type [semver:patch]

---

.circleci/config.yml
README.md

Migrating `master` branch to `main`. Details [here](https://staging.coda.io/d/Github-Rename-Migration-aka-The-Big-Rename_dZRtl44sES_/Primary-Branch-Rename_suIqj#_luiwG)

Master to Main Migration : [semver:minor]

---

src/commands/notify.yml
src/scripts/fetch_user_handles.sh

Add user name in details payload for sre to know who failed CI
Add err when github username not in the go/roster
changes per https://codaproject.slack.com/archives/C08ET52JE/p1614672977005800

Add user email and err message [semver:minor]

---

.circleci/config.yml
src/tests/test_user_handles.bats

Applies Dockerhub creds to avoid rate limits.

Apply Dockerhub credentials

---

.circleci/config.yml
README.md
src/@orb.yml
src/commands/notify.yml
src/commands/slack-notify-waiting-for-approval.yml
src/jobs/slack-notify-waiting-for-approval.yml
src/scripts/fetch_user_handles.sh
src/tests/test_user_handles.bats

Fix username issue and add slack notification message as parameter
https://krypton.app.opsgenie.com/alert/detail/0f80e628-57de-463d-b1da-49a2760b7f5a-1621037194580/details
Example of working failure 
Keeping in the slack notification parameter but will not add into other projects configs because catching the failure to send when failed is not working,, 
EX: https://github.com/coda/coda/commit/7112c9bbad66fad33ca1c2bc002ecfdc6ced732f is not sending failure slack notif so will get slack notifs in another PR or migrate to https://circleci.com/developer/orbs/orb/circleci/slack

Fix Username [semver:minor]

---

.circleci/config.yml

Consolidate CI Tokens [semver:minor] 

---

.circleci/config.yml

following -- https://circleci.com/developer/orbs/orb/circleci/orb-tools#commands-increment

remove ref

---

.circleci/config.yml
README.md
src/commands/send-alert.yml
src/commands/slack-notify-status.yml
src/examples/example.yml
src/jobs/cancel-older-awaiting-approvals.yml
src/jobs/slack-notify-waiting-for-approval.yml
src/message_templates/opsgenie_failure.json
src/message_templates/opsgenie_success.json
src/scripts/cancel_older_approvals.py
src/scripts/check_parallel.py
src/scripts/get_lkg_hash.py
src/scripts/opsgenie_alert.py

logic for running parallel

---

.circleci/config.yml

Using slack context variable over project variable

Add context depedency to slack [semver:patch]
